-- drop database grocery_db;
DROP DATABASE IF EXISTS grocery_db;
CREATE DATABASE grocery_db;
USE grocery_db;
SHOW TABLES;

-- 1. Suppliers Table
CREATE TABLE IF NOT EXISTS supplier (
    sup_id TINYINT PRIMARY KEY,
    sup_name VARCHAR(255),
    address TEXT
);

-- 2. Categories Table
CREATE TABLE IF NOT EXISTS categories (
    cat_id TINYINT PRIMARY KEY,
    cat_name VARCHAR(255)
);

-- 3. Employees Table
CREATE TABLE IF NOT EXISTS employees (
    emp_id TINYINT PRIMARY KEY,
    emp_name VARCHAR(255),
    hire_date VARCHAR(255)
);

-- 4. Customers Table
CREATE TABLE IF NOT EXISTS customers (
    cust_id SMALLINT PRIMARY KEY,
    cust_name VARCHAR(255),
    address TEXT
);

-- 5. Products Table
CREATE TABLE IF NOT EXISTS products (
    prod_id TINYINT PRIMARY KEY,
    prod_name VARCHAR(255),
    sup_id TINYINT,
    cat_id TINYINT,
    price DECIMAL(10,2),
    FOREIGN KEY (sup_id) REFERENCES suppliers(sup_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (cat_id) REFERENCES categories(cat_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

-- 6. Orders Table
CREATE TABLE IF NOT EXISTS orders (
    ord_id SMALLINT PRIMARY KEY,
    cust_id SMALLINT,
    emp_id TINYINT,
    order_date VARCHAR(255),
    FOREIGN KEY (cust_id) REFERENCES customers(cust_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (emp_id) REFERENCES employees(emp_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

-- 7. Order_Details Table
CREATE TABLE IF NOT EXISTS order_details (
    ord_detID SMALLINT AUTO_INCREMENT PRIMARY KEY,
    ord_id SMALLINT,
    prod_id TINYINT,
    quantity TINYINT,
    each_price DECIMAL(10,2),
    total_price DECIMAL(10,2),
    FOREIGN KEY (ord_id) REFERENCES orders(ord_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (prod_id) REFERENCES products(prod_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);
RENAME TABLE suppliers TO supplier;

SELECT * FROM products LIMIT 5;


SELECT * FROM supplier;
SELECT * FROM customers;



SELECT COUNT(*) as Total_Orders FROM orders;
SELECT COUNT(*) as Total_Items FROM order_details;

-- =======================================================
-- 1. CUSTOMER INSIGHTS
-- =======================================================

-- A. How many unique customers placed orders?
SELECT COUNT(DISTINCT cust_id) AS Unique_Customers FROM orders;

-- B. Which customers have placed the highest number of orders?
SELECT c.cust_name, COUNT(o.ord_id) AS Total_Orders 
FROM customers c JOIN orders o ON c.cust_id = o.cust_id 
GROUP BY c.cust_id ORDER BY Total_Orders DESC;

-- C. Total and Average purchase value per customer
SELECT c.cust_name, SUM(od.total_price) AS Total_Spent, AVG(od.total_price) AS Avg_Order_Value
FROM customers c JOIN orders o ON c.cust_id = o.cust_id 
JOIN order_details od ON o.ord_id = od.ord_id 
GROUP BY c.cust_id;

-- D. Top 5 Customers by total purchase amount
SELECT c.cust_name, SUM(od.total_price) AS Total_Revenue 
FROM customers c JOIN orders o ON c.cust_id = o.cust_id 
JOIN order_details od ON o.ord_id = od.ord_id 
GROUP BY c.cust_id ORDER BY Total_Revenue DESC LIMIT 5;

-- =======================================================
-- 2. PRODUCT PERFORMANCE
-- =======================================================

-- A. Products count in each category
SELECT cat.cat_name, COUNT(p.prod_id) AS Product_Count 
FROM categories cat JOIN products p ON cat.cat_id = p.cat_id 
GROUP BY cat.cat_id;

-- B. Average price of products by category
SELECT cat.cat_name, AVG(p.price) AS Avg_Price 
FROM categories cat JOIN products p ON cat.cat_id = p.cat_id 
GROUP BY cat.cat_id;

-- C. Highest sales volume (by quantity)
SELECT p.prod_name, SUM(od.quantity) AS Total_Qty_Sold 
FROM products p JOIN order_details od ON p.prod_id = od.prod_id 
GROUP BY p.prod_id ORDER BY Total_Qty_Sold DESC LIMIT 5;

-- D. Total revenue generated by each product
SELECT p.prod_name, SUM(od.total_price) AS Revenue 
FROM products p JOIN order_details od ON p.prod_id = od.prod_id 
GROUP BY p.prod_id ORDER BY Revenue DESC;

-- E. How do product sales vary by Category and Supplier?
SELECT 
    c.cat_name AS 'Category',
    s.sup_name AS 'Suppliers',
    SUM(od.total_price) AS 'Total_Revenue',
    SUM(od.quantity) AS 'Total_Units_Sold'
FROM 
    order_details od
JOIN 
    products p ON od.prod_id = p.prod_id
JOIN 
    categories c ON p.cat_id = c.cat_id
JOIN 
    supplier s ON p.sup_id = s.sup_id
GROUP BY 
    c.cat_name, s.sup_name
ORDER BY 
    Total_Revenue DESC;

-- =======================================================
-- 3. SALES AND ORDER TRENDS
-- =======================================================

-- A. Total orders placed
SELECT COUNT(*) AS Total_Orders FROM orders;

-- B. Average value per order
SELECT AVG(Order_Total) AS Avg_Order_Value 
FROM (SELECT ord_id, SUM(total_price) AS Order_Total FROM order_details GROUP BY ord_id) AS Table_Alies;

-- C. Most orders on which dates
SELECT order_date, COUNT(*) AS Orders_Count 
FROM orders GROUP BY order_date ORDER BY Orders_Count DESC LIMIT 5;

-- D. Monthly Trends: Orders & Revenue (Fixed)
SELECT 
    MONTHNAME(STR_TO_DATE(o.order_date, '%Y-%m-%d')) AS 'Month',
    COUNT(o.ord_id) AS 'Total_Orders_Volume',
    SUM(od.total_price) AS 'Total_Monthly_Revenue'
FROM 
    orders o
JOIN 
    order_details od ON o.ord_id = od.ord_id
GROUP BY 
    MONTHNAME(STR_TO_DATE(o.order_date, '%Y-%m-%d')), 
    MONTH(STR_TO_DATE(o.order_date, '%Y-%m-%d'))
ORDER BY 
    MONTH(STR_TO_DATE(o.order_date, '%Y-%m-%d'));
    
-- E. Weekday vs Weekend Order Patterns
SELECT 
    CASE 
        WHEN DAYOFWEEK(STR_TO_DATE(o.order_date, '%M %e, %Y')) IN (1, 7) THEN 'Weekend'
        ELSE 'Weekday'
    END AS Day_Pattern,
    COUNT(o.ord_id) AS Total_Orders,
    SUM(od.total_price) AS Total_Revenue
FROM 
    orders o
JOIN 
    order_details od ON o.ord_id = od.ord_id
GROUP BY 
    Day_Pattern;

-- =======================================================
-- 4. SUPPLIER CONTRIBUTION
-- =======================================================

-- A. Total suppliers count
SELECT COUNT(*) AS Total_Suppliers FROM supplier;

-- B. Supplier with most products
SELECT s.sup_name, COUNT(p.prod_id) AS Product_Count 
FROM supplier s JOIN products p ON s.sup_id = p.sup_id 
GROUP BY s.sup_id ORDER BY Product_Count DESC;

-- C. Average price per supplier
SELECT s.sup_name, AVG(p.price) AS Avg_Product_Price 
FROM supplier s JOIN products p ON s.sup_id = p.sup_id 
GROUP BY s.sup_id;

-- D. Suppliers contributing most to revenue
SELECT s.sup_name, SUM(od.total_price) AS Total_Revenue 
FROM supplier s JOIN products p ON s.sup_id = p.sup_id 
JOIN order_details od ON p.prod_id = od.prod_id 
GROUP BY s.sup_id ORDER BY Total_Revenue DESC;

-- =======================================================
-- 5. EMPLOYEE PERFORMANCE
-- =======================================================

-- A. Employees who processed orders
SELECT COUNT(DISTINCT e.emp_id) FROM employees e JOIN orders o ON e.emp_id = o.emp_id;

-- B. Employee with most orders
SELECT e.emp_name, COUNT(o.ord_id) AS Total_Orders_Handled 
FROM employees e JOIN orders o ON e.emp_id = o.emp_id 
GROUP BY e.emp_id ORDER BY Total_Orders_Handled DESC;

-- C. Total sales value processed by employee
SELECT e.emp_name, SUM(od.total_price) AS Total_Sales_Value 
FROM employees e JOIN orders o ON e.emp_id = o.emp_id 
JOIN order_details od ON o.ord_id = od.ord_id 
GROUP BY e.emp_id;

-- D. Average Order Value Handled Per Employee
SELECT 
    e.emp_name, 
    AVG(Order_Total) AS 'Avg_Order_Value_Per_Employee'
FROM 
    employees e
JOIN 
    orders o ON e.emp_id = o.emp_id
JOIN 
    (
        -- First: Calculate Total Price for EACH specific Order
        SELECT ord_id, SUM(total_price) AS Order_Total 
        FROM order_details 
        GROUP BY ord_id
    ) od_summary ON o.ord_id = od_summary.ord_id
GROUP BY 
    e.emp_id
ORDER BY 
    Avg_Order_Value_Per_Employee DESC;

-- =======================================================
-- 6. ORDER DETAILS DEEP DIVE
-- =======================================================

-- A. Relationship between Quantity ordered and Total Price (Correlation check)
SELECT AVG(quantity) as Avg_Qty, AVG(each_price) as Avg_Unit_Price, AVG(total_price) as Avg_Total_Price FROM order_details;

-- B. Average quantity ordered per product
SELECT p.prod_name, AVG(od.quantity) AS Avg_Qty_Per_Order 
FROM products p JOIN order_details od ON p.prod_id = od.prod_id 
GROUP BY p.prod_id ORDER BY Avg_Qty_Per_Order DESC;

-- C. Unit price variation
SELECT MIN(each_price) as Min_Price, MAX(each_price) as Max_Price FROM order_details;




